/**
 * generated by Xtext 2.13.0
 */
package org.xtext.whpp.mydsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.whpp.mydsl.WhRuntimeModule;
import org.xtext.whpp.mydsl.WhStandaloneSetup;
import org.xtext.whpp.mydsl.ide.WhIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class WhIdeSetup extends WhStandaloneSetup {
  @Override
  public Injector createInjector() {
    WhRuntimeModule _whRuntimeModule = new WhRuntimeModule();
    WhIdeModule _whIdeModule = new WhIdeModule();
    return Guice.createInjector(Modules2.mixin(_whRuntimeModule, _whIdeModule));
  }
}
