/**
 * generated by Xtext 2.13.0
 */
package org.xtext.whpp.mydsl.ide;

import org.xtext.whpp.mydsl.ide.AbstractWhIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class WhIdeModule extends AbstractWhIdeModule {
}
