/*
 * generated by Xtext 2.13.0
 */
package org.xtext.whpp.mydsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class WhAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/whpp/mydsl/parser/antlr/internal/InternalWh.tokens");
	}
}
