/**
 * generated by Xtext 2.13.0
 */
package org.xtext.whpp.mydsl;

import org.xtext.whpp.mydsl.AbstractWhRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class WhRuntimeModule extends AbstractWhRuntimeModule {
}
