/**
 * generated by Xtext 2.13.0
 */
package org.xtext.whpp.mydsl;

import org.xtext.whpp.mydsl.WhStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class WhStandaloneSetup extends WhStandaloneSetupGenerated {
  public static void doSetup() {
    new WhStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
