/*
 * generated by Xtext 2.13.0
 */
package org.xtext.whpp.mydsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.whpp.mydsl.ui.internal.MydslActivator;

public class WhUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MydslActivator.getInstance().getInjector("org.xtext.whpp.mydsl.Wh");
	}

}
