/**
 * generated by Xtext 2.13.0
 */
package org.xtext.whpp.mydsl.ui.contentassist;

import org.xtext.whpp.mydsl.ui.contentassist.AbstractWhProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class WhProposalProvider extends AbstractWhProposalProvider {
}
