/**
 * generated by Xtext 2.12.0
 */
package org.xtext.whpp.mydsl.wh;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Command</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.whpp.mydsl.wh.Command#getCommand <em>Command</em>}</li>
 *   <li>{@link org.xtext.whpp.mydsl.wh.Command#getVariables <em>Variables</em>}</li>
 *   <li>{@link org.xtext.whpp.mydsl.wh.Command#getExrps <em>Exrps</em>}</li>
 *   <li>{@link org.xtext.whpp.mydsl.wh.Command#getExpr <em>Expr</em>}</li>
 *   <li>{@link org.xtext.whpp.mydsl.wh.Command#getCommands <em>Commands</em>}</li>
 *   <li>{@link org.xtext.whpp.mydsl.wh.Command#getCommands_then <em>Commands then</em>}</li>
 *   <li>{@link org.xtext.whpp.mydsl.wh.Command#getCommands_else <em>Commands else</em>}</li>
 *   <li>{@link org.xtext.whpp.mydsl.wh.Command#getExpr_in <em>Expr in</em>}</li>
 * </ul>
 *
 * @see org.xtext.whpp.mydsl.wh.WhPackage#getCommand()
 * @model
 * @generated
 */
public interface Command extends EObject
{
  /**
   * Returns the value of the '<em><b>Command</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Command</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Command</em>' attribute.
   * @see #setCommand(String)
   * @see org.xtext.whpp.mydsl.wh.WhPackage#getCommand_Command()
   * @model
   * @generated
   */
  String getCommand();

  /**
   * Sets the value of the '{@link org.xtext.whpp.mydsl.wh.Command#getCommand <em>Command</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Command</em>' attribute.
   * @see #getCommand()
   * @generated
   */
  void setCommand(String value);

  /**
   * Returns the value of the '<em><b>Variables</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Variables</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variables</em>' containment reference.
   * @see #setVariables(Variables)
   * @see org.xtext.whpp.mydsl.wh.WhPackage#getCommand_Variables()
   * @model containment="true"
   * @generated
   */
  Variables getVariables();

  /**
   * Sets the value of the '{@link org.xtext.whpp.mydsl.wh.Command#getVariables <em>Variables</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Variables</em>' containment reference.
   * @see #getVariables()
   * @generated
   */
  void setVariables(Variables value);

  /**
   * Returns the value of the '<em><b>Exrps</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Exrps</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exrps</em>' containment reference.
   * @see #setExrps(Exprs)
   * @see org.xtext.whpp.mydsl.wh.WhPackage#getCommand_Exrps()
   * @model containment="true"
   * @generated
   */
  Exprs getExrps();

  /**
   * Sets the value of the '{@link org.xtext.whpp.mydsl.wh.Command#getExrps <em>Exrps</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exrps</em>' containment reference.
   * @see #getExrps()
   * @generated
   */
  void setExrps(Exprs value);

  /**
   * Returns the value of the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expr</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expr</em>' containment reference.
   * @see #setExpr(Expr)
   * @see org.xtext.whpp.mydsl.wh.WhPackage#getCommand_Expr()
   * @model containment="true"
   * @generated
   */
  Expr getExpr();

  /**
   * Sets the value of the '{@link org.xtext.whpp.mydsl.wh.Command#getExpr <em>Expr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expr</em>' containment reference.
   * @see #getExpr()
   * @generated
   */
  void setExpr(Expr value);

  /**
   * Returns the value of the '<em><b>Commands</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Commands</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Commands</em>' containment reference.
   * @see #setCommands(Commands)
   * @see org.xtext.whpp.mydsl.wh.WhPackage#getCommand_Commands()
   * @model containment="true"
   * @generated
   */
  Commands getCommands();

  /**
   * Sets the value of the '{@link org.xtext.whpp.mydsl.wh.Command#getCommands <em>Commands</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Commands</em>' containment reference.
   * @see #getCommands()
   * @generated
   */
  void setCommands(Commands value);

  /**
   * Returns the value of the '<em><b>Commands then</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Commands then</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Commands then</em>' containment reference.
   * @see #setCommands_then(Commands)
   * @see org.xtext.whpp.mydsl.wh.WhPackage#getCommand_Commands_then()
   * @model containment="true"
   * @generated
   */
  Commands getCommands_then();

  /**
   * Sets the value of the '{@link org.xtext.whpp.mydsl.wh.Command#getCommands_then <em>Commands then</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Commands then</em>' containment reference.
   * @see #getCommands_then()
   * @generated
   */
  void setCommands_then(Commands value);

  /**
   * Returns the value of the '<em><b>Commands else</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Commands else</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Commands else</em>' containment reference.
   * @see #setCommands_else(Commands)
   * @see org.xtext.whpp.mydsl.wh.WhPackage#getCommand_Commands_else()
   * @model containment="true"
   * @generated
   */
  Commands getCommands_else();

  /**
   * Sets the value of the '{@link org.xtext.whpp.mydsl.wh.Command#getCommands_else <em>Commands else</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Commands else</em>' containment reference.
   * @see #getCommands_else()
   * @generated
   */
  void setCommands_else(Commands value);

  /**
   * Returns the value of the '<em><b>Expr in</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expr in</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expr in</em>' containment reference.
   * @see #setExpr_in(Expr)
   * @see org.xtext.whpp.mydsl.wh.WhPackage#getCommand_Expr_in()
   * @model containment="true"
   * @generated
   */
  Expr getExpr_in();

  /**
   * Sets the value of the '{@link org.xtext.whpp.mydsl.wh.Command#getExpr_in <em>Expr in</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expr in</em>' containment reference.
   * @see #getExpr_in()
   * @generated
   */
  void setExpr_in(Expr value);

} // Command
