/**
 * generated by Xtext 2.13.0
 */
package org.xtext.whpp.mydsl.wh;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expror</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.whpp.mydsl.wh.Expror#getExprG <em>Expr G</em>}</li>
 *   <li>{@link org.xtext.whpp.mydsl.wh.Expror#getExpr <em>Expr</em>}</li>
 *   <li>{@link org.xtext.whpp.mydsl.wh.Expror#getExprD <em>Expr D</em>}</li>
 * </ul>
 *
 * @see org.xtext.whpp.mydsl.wh.WhPackage#getExpror()
 * @model
 * @generated
 */
public interface Expror extends EObject
{
  /**
   * Returns the value of the '<em><b>Expr G</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expr G</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expr G</em>' containment reference.
   * @see #setExprG(Exprnot)
   * @see org.xtext.whpp.mydsl.wh.WhPackage#getExpror_ExprG()
   * @model containment="true"
   * @generated
   */
  Exprnot getExprG();

  /**
   * Sets the value of the '{@link org.xtext.whpp.mydsl.wh.Expror#getExprG <em>Expr G</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expr G</em>' containment reference.
   * @see #getExprG()
   * @generated
   */
  void setExprG(Exprnot value);

  /**
   * Returns the value of the '<em><b>Expr</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expr</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expr</em>' attribute.
   * @see #setExpr(String)
   * @see org.xtext.whpp.mydsl.wh.WhPackage#getExpror_Expr()
   * @model
   * @generated
   */
  String getExpr();

  /**
   * Sets the value of the '{@link org.xtext.whpp.mydsl.wh.Expror#getExpr <em>Expr</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expr</em>' attribute.
   * @see #getExpr()
   * @generated
   */
  void setExpr(String value);

  /**
   * Returns the value of the '<em><b>Expr D</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expr D</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expr D</em>' containment reference.
   * @see #setExprD(Expror)
   * @see org.xtext.whpp.mydsl.wh.WhPackage#getExpror_ExprD()
   * @model containment="true"
   * @generated
   */
  Expror getExprD();

  /**
   * Sets the value of the '{@link org.xtext.whpp.mydsl.wh.Expror#getExprD <em>Expr D</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expr D</em>' containment reference.
   * @see #getExprD()
   * @generated
   */
  void setExprD(Expror value);

} // Expror
